# Audit all gems listed in the Gemfile for known security problems by running bin/bundler-audit.
# CVEs that are not relevant to the application can be enumerated on the ignore list below.

ignore:
  - GHSA-53p3-c7vp-4mcc
  - CVE-2026-33306
